language: node_js
node_js:
  - stable
addons:
  browserstack:
    username: "bertrandberthelo1"
    access_key:
      secure: "FSJvfvEX6C4OAM6ZF/bQdS718N/IOCeErBljObyWlJ6NoLakIsIp9ssYiNcVQHtUdTuuHOuIdLxjPqMoxQkZtoHS2oZ1wg7veaN/wl+5HuxeaOvHxahNlxT7Z0FzQgxiHDFTHsXP2a+vDtEGjCIdvvcurR/2cK2gkfSFJ5NeeXY="
branches:
  only:
    - master
    - development
    - /(release).*/
stages:
  - build
  - deploy
  - name: test
    # Run test stage only if cron job
    if: type = cron
env:
  global:
    - ENCRYPTION_LABEL: 98a7d362e1e4
  matrix:
    - BROWSER=chrome
    - BROWSER=ie
    - BROWSER=edge
#    - BROWSER=firefox
before_install:
  - npm install -g gulp
install:
  - npm install
jobs:
  include:
    - stage: build
      script:
        # Build the source files
        - npm run build
        # Build/generate the jsdoc
        - npm run doc
        - |
          if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "development" ]; then
            # Package and deploy version on project's pages
            openssl aes-256-cbc -K $encrypted_f186f3e7458a_key -iv $encrypted_f186f3e7458a_iv -in travis_deploy.enc -out travis_deploy -d
            chmod 600 travis_deploy
            eval `ssh-agent -s`
            ssh-add travis_deploy
            npm run deploy
          fi
deploy:
  api_key:
    secure: fLr/s6xT5T2mh2UaPUtt3UlkdmvRkqzOlolJss3c6OICeFegFmx/ieuf8iACnB5u3fZ1pgY9/wIXq9f6uKUpTsDQd/B0uALpe/Nzv/OFGkC1S8qk66Z9VC4/LNkDSEOryAKDDPwMgcZgxyPe5u20NrVUKahMB0B4vhYKwGle5LQ=
  on:
    branch: master
    tags: true
  skip_cleanup: true
